export const STORAGE_KEYS = {
    AUTH_TOKEN: 'AUTH_TOKEN',
    ACCESS_TOKEN: 'AUTH_TOKEN', // alias for consistency
    USER_DATA: 'USER_DATA',
    SUBSCRIBED_CHANNELS: 'SUBSCRIBED_CHANNELS',
    USER_CHANNEL: 'USER_CHANNEL',
    DRIVER_CHANNEL: 'DRIVER_CHANNEL',
    PENDING_EMERGENCY_REQUEST: 'PENDING_EMERGENCY_REQUEST',
    ACTIVE_BACKGROUND_TRIP: 'ACTIVE_BACKGROUND_TRIP',
} as const;